### ISSUE TITLE
Yugioh card Images broken

### ISSUE THREAD

**Issue by mat3osz** [Obtuse-Goose/AutocardAnywhere#2]
Pop-ups are not loading YuGiOh card images properly. "broken-image" class added everytime. Checked on Edge, Chrome, Opera. Same for all of browsers. Probably YGOPro changed API calls for images.

**Comment by qqzm** [comment]
Hi,
You are correct, YGOPro have changed their image api.
I've released a fixed version - 4.29.0 If you update to that it should now be working again.

Thanks for letting me know,
Stephen
