### ISSUE TITLE
Netrunner card images are broken in 4.29.0 on Firefox

### ISSUE THREAD

**Issue by SpencerDub** [Obtuse-Goose/AutocardAnywhere#3]
## Summary
Netrunner cards are recognized by AutocardAnywhere, but when hovering over the autocard links, only broken images are displayed.

## System Specs
* Browser: Firefox 116.0.3 (64-bit), snap version for Ubuntu
* AutocardAnywhere version: 4.29.0

## Steps to reproduce
1. Enable AutocardAnywhere with Netrunner support.
2. Visit [this page](https://netrunnerdb.com/en/card/30075) and look for autocard'd links in the card reviews. Or visit this very page, where I've said the following: Sure Gamble, Hedge Fund, Overclock, Stimhack
3. Hover over one such link.

## Expected behavior
An image of the linked card appears in the hover

## Encountered behavior
A broken image (a red rectangle with a "broken image" icon) appears in the hover

## Additional information
A NetrunnerDB developer has said the following regarding changes to the NetrunnerDB API and image naming:

> 
> Old API is v2.  Calls like: `https://netrunnerdb.com/api/2.0/public/card/33001`
> have 
> `"imageUrlTemplate": "https://card-images.netrunnerdb.com/v1/large/{code}.jpg",`
> and then you can replace the code.
> New API is v3 and there are 2 things different. 
> 1 -> Cards in V3 are the unique cards, not printings, so they don't have images.  Printings in v3 are equivalent to cards in v2
> Ids for printings are the same as ids for cards in V2.
> and the printing images are available in the images attribute, with support for named sets of images:
> ```
> "images": {
> "nrdb_classic": {
> "tiny": "https://card-images.netrunnerdb.com/v1/tiny/30055.jpg",
> "small": "https://card-images.netrunnerdb.com/v1/small/30055.jpg",
> "medium": "https://card-images.netrunnerdb.com/v1/medium/30055.jpg",
> "large": "https://card-images.netrunnerdb.com/v1/large/30055.jpg"
> }
> },
> ```

Additional documentation of the new NetrunnerDB API can be found [here](https://api-preview.netrunnerdb.com/api/docs/).

**Comment by qqzm** [comment]
I've just released version 4.30.0 which should fix this issue. It's available now on Firefox and Opera. Chrome and Edge are waiting review - Chrome is usually within a day, Edge is about 2 weeks.
