### ISSUE TITLE
[Firefox 4.34.0] Cardmarket prices not showing

### ISSUE THREAD

**Issue by Stainless2k** [Obtuse-Goose/AutocardAnywhere#5]
Cardmarket prices are not shown anymore. I'm using Firefox 124.0.1 on Arch Linux.

![Screenshot from 2024-04-05 17-41-26](https://github.com/Obtuse-Goose/AutocardAnywhere/assets/5407961/5997908a-7a34-432e-9cff-063bc8336504)
![Screenshot from 2024-04-05 17-41-58](https://github.com/Obtuse-Goose/AutocardAnywhere/assets/5407961/8b46c24e-5b51-45a8-80ae-03381a1fbecd)

**Comment by Stainless2k** [comment]
TCG player prices are also not shown, so no prices are shown :sweat_smile:

**Comment by qqzm** [comment]
Hi,
I've just published version 4.35.0 that fixes this issue. If you update your extension it should correctly show the prices.

Thanks for letting me know,
Stephen
